CREATE TABLE locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city TEXT NOT NULL,
    state_province TEXT NOT NULL,
    country TEXT NOT NULL,
    unique_loc TEXT NOT NULL
);