CREATE TABLE destinations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    destination TEXT NOT NULL,
    sequence_num INTEGER NOT NULL,
    content TEXT,
    dest_address TEXT NOT NULL,
    dest_lat NUMERIC NOT NULL,
    dest_lng NUMERIC NOT NULL,
    place_id TEXT NOT NULL,
    formatted_address TEXT NOT NULL,
    route_id INTEGER
        REFERENCES routes(id) ON DELETE CASCADE NOT NULL
);